apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: ticketing
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: ticketing
data:
  init-dbs.sql: |
    CREATE DATABASE auth_db;
    CREATE DATABASE booking_db;
    CREATE DATABASE seat_inventory_db;
    CREATE DATABASE payment_db;
    CREATE DATABASE notification_db;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "ticketing"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ticketing-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "ticketing"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "ticketing"]
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-scripts
          configMap:
            name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ticketing
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432


